### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by ghost** [janimo/textsecure-qml#14]
Hello!
First of all thanks for creating an app that people can use on Ubuntu Phone. I own an Android but to be honest all the developers like you are making me want to switch to Ubuntu. So thanks!
I'd suggest a couple of things:
1. Rename the app into "Signal". Now that the Android app is called Signal too, ubuntu would be the only OS having the old name. And I wouldn't worry about the fact that it doesn't make calls yet, the browser extension doesn't either but it's called Signal anyway.
2. Use Transifex to translate strings. I know that at the moment there aren't many users - especially worldwide, but the sooner you start using it the better, right? :) And there are people like me who would still help even if we don't have an ubuntu phone (yet?).

Thanks!

**Comment by elimisteve** [comment]
Hi @oaim,

First of all, I am also on Android, and my next phone will be an Ubuntu Phone :-).  So I feel similarly to you.
1. Are you sure?  The Android apps are still split into TextSecure and RedPhone; I have both of them installed now, and don't see Signal (like there exists for iOS): https://play.google.com/store/apps/developer?id=Open+Whisper+Systems
2. Agreed; good idea!

**Comment by janimo** [comment]
Hi,

1) indeed, TextSecure and RedPhone merged in git master and will ikely be
released as Signal soon. I will probably change the name at one point as
well, it had not been a priority yet.

2) There's an issue filed for i18n already. The app needs to be made 18n
ready and then I think lifting most translations from TextSecure/Signal on
Android will be good enough, as I intend to reuse their UI strings as much
as possible.

**Comment by bartz1** [comment]
I agree, renaming TextSecure to Signal would be better now that the Android app is in beta (and will be release in not more than just a few days). Thank you for your awesome work! You're faster at developing than moxie, hahaha

**Comment by bartz1** [comment]
A lot of people are downloading Signal these days and I wouldn't be surpirsed if people were looking it up on the ubuntu store too. But they won't find it as long as it's called textsecure. This may be the right chance to update the name! :)

**Comment by janimo** [comment]
Searching for Signal works, it's already added as a search keyword for the
app - seacrhes are not by name only
