### ISSUE TITLE
Donating

### ISSUE THREAD

**Issue by ghost** [janimo/textsecure-qml#15]
Could you give us a way to donate, like through a website or something? It would be cool if we could support you this way -- and you could give a small percentage of the donations to whispersystems too.

**Comment by janimo** [comment]
Thanks, but feel free to direct any amount you would like to donate to Whispersystems or the EFF or any similar organization. Unless you can donate spare time, bugreports or code I am not sure you can help get this move faster ;)

**Comment by Pazuu** [comment]
Janimo just thank you! :)
