### ISSUE TITLE
Conversation stops if peer changes identity (when reinstalling their app for example)

### ISSUE THREAD

**Issue by ChrisLuck** [janimo/textsecure-qml#21]
Currently the UI shows me an open session with a friend (android).
We can't write each other in this session, all messages get lost.

The log in upstart folder says "ERRO[0008] invalid message: no valid sessions"
And indeed, there is no session file for this contact in the sessions folder.

I guess the only way to get rid of this zombie session is to delete and reinstall textsecure. I can't find a way in the UI to terminate a session.

That friend got a new phone last week, maybe that's the reason for the bug?

Logfile:
http://paste.ubuntu.com/12972957/

**Comment by janimo** [comment]
So 'reset the session' does not go through either?
You could try manually removing the
~/.local/share/textsecure.jani/.storage/identity/remote_xxxxx
for this identity.

Indeed, him reinstalling textsecure (would be the same even if he reinstalled on the same phone) got him a new identity (public key) on the server, and I do not yet handle the identity being changed.
I guess I need to bump the priority of this.
For now, delete that file manually and it should be regarded then as first contact, which is always trusted.

**Comment by ChrisLuck** [comment]
I see, so this is more a missing feature than a bug ;)
Session reset didn't work (clock symbol).
Deleting the remote_xxxx file and restarting textsecure worked perfectly.
After that, I also got an old message he sent me yesterday :P

**Comment by janimo** [comment]
Well it's a bug from a user's point of view :)

**Comment by janimo** [comment]
Fixed (worked around) in 0.3.5. The app will now silently accept the new identities of peers. This needs to be exposed in the UI so the user is alerted of the change.
