### ISSUE TITLE
Lost video and message

### ISSUE THREAD

**Issue by ChrisLuck** [janimo/textsecure-qml#22]
A friend sent me a video file from his android phone.
Instead of the video file I received an empty text-box.
I answered him in two seperate messages, the first one got lost (but i got double tick symbol).
The second message was sent and received correctly.

**Comment by janimo** [comment]
so two bugs I think
1) the video you received did not show (empty textbox means it was probably not detected as a video file).
Can you look under ~/.local/share/textsecure.jani/attachments/ and try figuring out which of those files with long hex names is the problematic video (depending on the version you use, it may or may not have an )extension) by running file on them and possibly ls to see the timestamp.
Let me know what file says about the file, and also what the output of head -c 128 $filename|xxd is

There are many types of videos and our mime-type detection is not covering most of them.

2) This is strange, double tick means we got a receipt message for that message. Please see whether you have a 'Message with timestamp xxxxx not found' in the logs.

**Comment by ChrisLuck** [comment]
Ok, here are the results :)

phablet@ubuntu-phablet:~/.local/share/textsecure.jani/attachments$ file ebfda4e580b949c7d5eec293b780ac5a 
ebfda4e580b949c7d5eec293b780ac5a: ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]

phablet@ubuntu-phablet:~/.local/share/textsecure.jani/attachments$ head -c 128 ebfda4e580b949c7d5eec293b780ac5a|xxd
0000000: 0000 0020 6674 7970 6973 6f6d 0000 0200  ... ftypisom....
0000010: 6973 6f6d 6973 6f32 6176 6331 6d70 3431  isomiso2avc1mp41
0000020: 0000 0a22 6d6f 6f76 0000 006c 6d76 6864  ..."moov...lmvhd
0000030: 0000 0000 0000 0000 0000 0000 0000 03e8  ................
0000040: 0000 3a98 0001 0000 0100 0000 0000 0000  ..:.............
0000050: 0000 0000 0001 0000 0000 0000 0000 0000  ................
0000060: 0000 0000 0001 0000 0000 0000 0000 0000  ................
0000070: 0000 0000 4000 0000 0000 0000 0000 0000  ....@...........

Unfortunately I don't have a log for this bug. The log that is closest to the occurence of the bug is the one i already posted in the other issue:
http://paste.ubuntu.com/12972957/

How does the logging system work? is the log overwritten on boot or on app-start ?

**Comment by janimo** [comment]
It is indeed an mp4 type that is not detected. I'll look into this.

Old logs are gzipped when a new is started. So you'll likely have
application-click-textsecure.jani_textsecure_0.3.3.log.1.gz or similar there.

**Comment by janimo** [comment]
BTW you can probably make the video show up by doing this from the command line:

sqlite3 /home/phablet/.local/share/textsecure.jani/db/db.sql "update  messages set ctype=5 where attachment like '%ebfda4e580b949c7d5eec293b780ac5a%'"

and the restart the app.

Whether you can play back the video is another question - playback is unreliable.

**Comment by janimo** [comment]
Video attachment detection was improved in 0.3.4 so this should no longer happen.
