### ISSUE TITLE
Sort conversations by time/date

### ISSUE THREAD

**Issue by HF-B5** [janimo/textsecure-qml#32]
Hi,

I appreciate you work to bring TextSecure to Ubuntu-Phone. Well done!

One wish from my side is to allow sorting the conversations by time/date. Currently a new message 
in a conversation may be hidden somewhere down the list, you have to scroll down to find it.

**Comment by janimo** [comment]
Thanks, known issue and on the roadmap. I'll bump its priority :)

**Comment by janimo** [comment]
In 0.3.8

**Comment by HF-B5** [comment]
Many thanks!

On 2015-12-02 00:52, Jani Monoses wrote:

> In 0.3.8
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/janimo/textsecure-qml/issues/32#issuecomment-161134750

## 

helmut@franzke.de helmut-s@franzke.de

## PGP key fingerprint = 44DF 55B3 81C3 FAA6 6535  7995 FD99 4708 D33B BD63

Work less - Sail more
Brueder und Schwestern, auf zur Sonne, zur Freizeit!
                  ,~
                  |\
                 /| \
         ~^~ ^~ /_|__~^~ ~^~
        ~^~^ ~ '======' ~^ ~^~

##     jgs  ~^~ ~^ ~^~ ~^~ ~^ ~

NO ADS, NO HTML-MAIL, NO ATTACHEMENTS IN PROPRIETARY FORMATS
