### ISSUE TITLE
Textsecure freezes while importing contacts on BQ4.5

### ISSUE THREAD

**Issue by teertinker** [janimo/textsecure-qml#33]
Hello I never actually got one contact imported. 
# Procedure:

Start Textsecure
-On Startup: Error Message: Switching to unencrypted session for now.
- click OK
- add contact via contacts app
- click on one contact (format: +49176....) -> note: I don't acutally know whom of my contact does use textsecure, so its possible the recipient doesn't use it.
  than:
- either textsecure frezzes while the importing contacts window is still there
- or if contacts app was open before: textsecure crashes 
# Narrowing down the bug:

A log file "/home/phablet/.cache/upstart/application-click-textsecure.jani_textsecure_0.3.*.log"
does not exist. 
- I am on wireless lan without connectivity issues.

**Comment by janimo** [comment]
Thanks for the thorough report!

Does the 'Switching to unencrypted session' error also say
rm -Rf /home/phablet/.local/share/textsecure.jani/.storage ?

That should be done on the phone.

Did you use the app when it was a 0.2.x version? With 0.3.0 the storage changed and that error should only be shown when switching from old to new format.

The log file should also be on the phone, and you can get it by doing
adb pull /home/phablet/.cache/upstart/application-click-textsecure.jani_textsecure_0.3.7.log

So your crash may be related to the app not starting ok due to that error. I need to fix that so it does not continue at all in that case.

When importing you should usually check all contacts (top header of the selector) instead of unique contacts. Then the app will figure out which of your contacts is using Signal and show them.

**Comment by teertinker** [comment]
"Does the 'Switching to unencrypted session' error also say
rm -Rf /home/phablet/.local/share/textsecure.jani/.storage ?"

-> yes

"Did you use the app when it was a 0.2.x version? With 0.3.0 the storage changed and that error should only be shown when switching from old to new format."

-> I installed each update and tried textsecure. So yes. But importing contacts never worked.

"The log file should also be on the phone, and you can get it by doing
adb pull /home/phablet/.cache/upstart/application-click-textsecure.jani_textsecure_0.3.7.log"
- I looked for the file with filemanager. I didn't show up. Your command states: "bash: adb: command not found"

"When importing you should usually check all contacts (top header of the selector) instead of unique contacts. Then the app will figure out which of your contacts is using Signal and show them."

I did try that as well. Than I thought may be there is an error due to some contacts, which is why I tried to import only one.

**Comment by janimo** [comment]
Do you use Ubuntu on your computer?
If so adb is in the package android-tools-adb

So the root of the issue is, the app is in an inconsistent state until that file is deleted. I will fix that in the next version by having the app delete the file itself

**Comment by teertinker** [comment]
"Do you use Ubuntu on your computer?
If so adb is in the package android-tools-adb"

Ok, so you mean I should use the PC Terminal. I did use the phone terminal-app. Using the PC Terminal in phone developer mode I get:

_remote object '/home/phablet/.cache/upstart/application-click-textsecure.jani_textsecure_0.3.7.log' does not exist_

"So the root of the issue is, the app is in an inconsistent state until that file is deleted. I will fix that in the next version by having the app delete the file itself"
- could deleting the app and reinstalling it help?

**Comment by janimo** [comment]
Phone terminal should have been ok. I thought you were trying to look at /home/phablet on your PC.
Is there any textsecure log there at all?
What does ls -l /home/phablet/.cache/upstart/application-click-textsecure.jani_textsecure\* say

**Comment by teertinker** [comment]
Sorry, there is no file related to textsecure in my upstart folder.

**Comment by janimo** [comment]
Ok, I'll try to fix this automatically in 0.3.8 soon.

**Comment by janimo** [comment]
Can you try and see if 0.3.8 behaves differently? It should delete that dir instead of asking the user to.

**Comment by janimo** [comment]
solved. There was a confusion due to a phone number change at the user.
