### ISSUE TITLE
Account can't be removed

### ISSUE THREAD

**Issue by SidPayton** [janimo/textsecure-qml#38]
It was finally possible to Register with the app. But I Used another account just to test it. Now I can't remove it and put my own details in.

**Comment by janimo** [comment]
You mean you registered using another phone number, and now want to use your own?

**Comment by SidPayton** [comment]
Yes. Thats exactly what I want. How is that possible?

**Comment by janimo** [comment]
For now you can adb shell intro the phone and rm -Rf /home/phablet/.local/share/textsecure.jani/ and rm -Rf /home/jani/.config/textsecure.jani . This will drop all your existing app-related data.
Then you start the app.
I will add an UI for this in the upcoming release.

**Comment by janimo** [comment]
There's a UI for this under Settings/Advanced in version 0.3.10
