### ISSUE TITLE
show time of last sync with server

### ISSUE THREAD

**Issue by AnneGilles** [janimo/textsecure-qml#39]
I understand that the app queries the server once in a while. the default view listing all the conversations can be pulled down -- a guesture known from other touch devices. this should trigger a reload and or show the last time of (or time since) refresh/api call.

as long as we don't have notifications coming, that would be nice.

**Comment by janimo** [comment]
The inbox view (list of all conversation) should be updated in real time, as the connection between the app and the server is via a websocket. There is no polling, the server pushes as soon as it has a message. Do you notice a lack of updates or a delay?

**Comment by AnneGilles** [comment]
yes, websocket. 

yes, I do notice lack of updates and delays sometimes, which is ok with me. I also do notice the short freezes mentioned by someone else before, sometimes even "blurry" (less sharp rendering) screens.

I do not see if the socket is on/open/active or not. That would be helpful, though, imho. For example when I change networks, commute, roam, I would like to see if there is a connection/socket or not. and since when there is not.

**Comment by janimo** [comment]
I try to keep as close to the Android UX as possible. Not sure they have anything resembling this, although they have clear errors when the network is down and an operation (other than messaging, those are queued) is requested such registering or sending a debug log.

**Comment by janimo** [comment]
Unless there's some concrete UI that is in Android and that we can add I'd rather close this one.

**Comment by AnneGilles** [comment]
I have no android or iOS to test or compare, so you choose.
