### ISSUE TITLE
info about new contact (message induced) is not taken from address book

### ISSUE THREAD

**Issue by AnneGilles** [janimo/textsecure-qml#40]
I just invited a friend to use signal (android) and find me and message me. so a new conversation popped up. that worked fine.

That contact is not updated with known info from the adress book, mainly the persons name. I just see that conversation listed under his number. Do I have to sync contacts with address book? This should happen automatically, imho.

**Comment by janimo** [comment]
When the contact messaged you, did you have them in your address book, or added them afterwards?
Address book is not synced automatically because it must be interactive, normal apps do not have the permission to read the address book.

**Comment by janimo** [comment]
But I know this is a bug, and it can be fixed.

**Comment by AnneGilles** [comment]
yes, I had had him in the address book before.

**Comment by janimo** [comment]
Does upgrading to 0.3.10 fix this?

**Comment by janimo** [comment]
ping

**Comment by AnneGilles** [comment]
yes, that one was fixed in 0.3.10: contacts name was loaded from address book after upgrade.

since then, one contact popped up in TextSecure that I did not have in the address book, which I added later. That contact has not been 'synced' with the address book, so I still have him listed in the conversations view with his number only.

**Comment by janimo** [comment]
You need to sync the address book manually from time to time. It is not automatic because unlike on Android it prompts the user, so it would be annoying to pop it up periodically.

Just go to the contacts page (pencil) and push refresh (reload icon)
