### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by luxpir** [janimo/textsecure-qml#46]
Not able to stop the client crashing on load at the moment- it may have started following a system crash/auto restart. Seen this before, any ideas?

Reminds me of dekko not loading due to a lock file, except this closes the signal instance within a second of opening.

**Comment by janimo** [comment]
Can you check the app logs? No idea off the top of my head.

**Comment by luxpir** [comment]
Sure - thanks - it says:

```
[34mINFO[0m[0000] Setup completed
[37mDEBU[0m[2016/12/13 12:28:59] PUT /v1/directory/tokens 200
```

Every time I open it and it closes itself.

The last one prior to those open/closes says:

```
[37mDEBU[0m[2016/12/12 18:50:22] PUT /v1/messages/+[phonenum] 404
[34mINFO[0m[2016/12/12 18:50:22] status code 404
[31mERRO[0m[2016/12/12 18:50:22] use of closed network connection

[37mDEBU[0m[2016/12/12 18:50:52] PUT /v1/messages/+[samephonenum] 404
[34mINFO[0m[2016/12/12 18:50:52] status code 404
[37mDEBU[0m[2016/12/12 18:50:52] PUT /v1/messages/+[samephonenum] 404
[34mINFO[0m[2016/12/12 18:50:52] status code 404
[34mINFO[0m[2016/12/12 18:51:12] EOF
```

And that message repeats dozens times before then. It isn't unreasonable to suspect that the number in the logs might be disconnected - any way I can remove those pending messages to that number manually? Or is that not what's holding it up. Can't find the v1 directory so far...

Cheers

**Comment by janimo** [comment]
v1/messages is an API endpoint on the Signal servers, not a local path.
PUT v1/messages is sending a message to the given number via the server.

Removing pending messages manually could be done by removing the corresponding session altogether under
~/.local/share/textsecure.jani/.storage/sessions/

Probably removing more things under storage would allow the app to start. You could debug that by moving bits of the storage directory aside one by one, but I think that one of the sessions is the problem.

**Comment by luxpir** [comment]
Yep, you got it. I removed the latest session, with the same filename as the phone-number in the logs and boom, we're in.

Many thanks for your time and your work!

**Comment by janimo** [comment]
thanks, this still is a bug that needs fixing, but I have not  touched the code over 9 months :/
