### ISSUE TITLE
Publish on the OpenStore

### ISSUE THREAD

**Issue by NeoTheThird** [janimo/textsecure-qml#49]
Since the canonical click store might be discontinued soon, it'd be awesome to have this app on the OpenStore: https://openstore.ubports.com

Thank you!

**Comment by timothymctim** [comment]
[nanu-c's fork](https://github.com/nanu-c/textsecure-qml) of this app got published under the name Signal to the OpenStore.

**Comment by NeoTheThird** [comment]
Right, forgot to close this one.
